

GET {{baseUrl}}/api/brand/findById
	?subset=A
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/brand/findMany
	?subset=A
	&params[num]=24
	&params[page]=1
	&params[search]=id
	&params[keyword]=KEYWORD
	&params[orderBy]=id-desc
	&params[queryMode]=both
	&params[id]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/brand/save
Content-Type: application/json

{ "saveParamsArray": [{ "id": 0, "name": "NAME", "created_at": "2000-01-01" }] }


###

GET {{baseUrl}}/api/brand/del
	?ids[0]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/brand/attach
Content-Type: application/json

{ "ids": [0], "what": "WHAT" }


###

POST {{baseUrl}}/api/file/upload
Content-Type: application/json

{}


###

GET {{baseUrl}}/api/post/findById
	?subset=A
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/post/findMany
	?subset=A
	&params[num]=24
	&params[page]=1
	&params[search]=title
	&params[keyword]=KEYWORD
	&params[orderBy]=id-desc
	&params[queryMode]=both
	&params[id]=0
	&params[type]=a-notice
	&params[status]=ready
Content-Type: application/json

###

POST {{baseUrl}}/api/post/save
Content-Type: application/json

{
  "saveParamsArray": [
    {
      "id": 0,
      "type": "a-notice",
      "title": null,
      "content": "CONTENT",
      "status": "ready",
      "rating": null,
      "source_url": null,
      "is_public": false,
      "created_at": "2000-01-01",
      "images": ["IMAGES"]
    }
  ]
}


###

GET {{baseUrl}}/api/post/del
	?ids[0]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/post/like
Content-Type: application/json

{ "id": 0 }


###

GET {{baseUrl}}/api/product/findById
	?subset=A
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/product/findMany
	?subset=A
	&params[num]=24
	&params[page]=1
	&params[search]=title
	&params[keyword]=KEYWORD
	&params[orderBy]=id-desc
	&params[queryMode]=both
	&params[id]=0
	&params[type]=craft
	&params[status]=active
	&params[brand_id]=0
	&params[tag_id]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/product/save
Content-Type: application/json

{
  "saveParamsArray": [
    {
      "id": 0,
      "brand_id": 0,
      "type": "craft",
      "title": "TITLE",
      "description": "DESCRIPTION",
      "price": 0,
      "is_new": false,
      "visible_until_at": "2000-01-01",
      "status": "active",
      "created_at": "2000-01-01",
      "checked_at": null,
      "images": ["IMAGES"],
      "tags": [{ "id": 0, "name": "NAME" }]
    }
  ]
}


###

GET {{baseUrl}}/api/product/del
	?ids[0]=0
Content-Type: application/json

###

GET {{baseUrl}}/api/tag/findById
	?subset=A
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/tag/findMany
	?subset=A
	&params[num]=24
	&params[page]=1
	&params[search]=id
	&params[keyword]=KEYWORD
	&params[orderBy]=id-desc
	&params[queryMode]=both
	&params[id]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/tag/save
Content-Type: application/json

{ "saveParamsArray": [{ "id": 0, "name": "NAME" }] }


###

GET {{baseUrl}}/api/tag/del
	?ids[0]=0
Content-Type: application/json

###

GET {{baseUrl}}/api/user/findById
	?subset=A
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/user/findMany
	?subset=A
	&params[num]=24
	&params[page]=1
	&params[search]=name
	&params[keyword]=KEYWORD
	&params[orderBy]=id-desc
	&params[queryMode]=both
	&params[id]=0
	&params[role]=normal
	&params[status]=ready
Content-Type: application/json

###

POST {{baseUrl}}/api/user/login
Content-Type: application/json

{ "loginParams": { "string_id": "STRING_ID", "pw": "PW" } }


###

GET {{baseUrl}}/api/user/me
	?
Content-Type: application/json

###

GET {{baseUrl}}/api/user/logout
	?
Content-Type: application/json

###

GET {{baseUrl}}/api/user/test1
	?
Content-Type: application/json