// tsup.config.js
import { defineConfig } from "tsup";
import { ImportToRequirePlugin } from "./import-to-require";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/bin/cli.ts",
    "src/bin/cli-wrapper.ts",
    "src/database/drivers/knex/base-model.ts",
    "src/database/drivers/kysely/base-model.ts",
  ],
  dts: true,
  format: ["cjs", "esm"],
  target: "esnext",
  clean: true,
  sourcemap: true,
  shims: true,
  platform: "node",
  splitting: true,
  esbuildPlugins: [ImportToRequirePlugin],
  external: [
    "chalk",
    "dotenv",
    "fast-deep-equal",
    "fastify",
    "fs-extra",
    "glob",
    "inflection",
    "knex",
    "lodash",
    "luxon",
    "mysql2",
    "node-sql-parser",
    "prompts",
    "qs",
    "tsicli",
    "uuid",
    "zod",
    "prettier",
    "source-map-support",
    "tsup",
    "typescript",
  ],
});
